# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IIjr8lXn0AfssCxk4c0YktT-arQASsNH
"""

#Solicita o nome do Usuário e pergunta se quer fazer um calculo para caso não, possa encerrar o programa
nome = input("Digite seu nome:")
print(f"Ola {nome}! Bem vindo a Calculadora inteligente do Allan, qual operação gostaria de realizar um operação? (Sim/Não)")
calcFazer = input()

while calcFazer == "Sim":
  num1 = float(input("Digite o primeiro número:")) #Solicita os dois números para a operação e depois pergunta qual operação deseja fazer
  num2 = float(input("Digite o segundo número:"))
  tipoOperacao = input("Que tipo de operação você gostaria de fazer (+, -, x, /):")
  if tipoOperacao == "+":
    resultado = num1 + num2
    print(f"O resultado da operação é: {resultado}")
    calcFazer = input("Deseja fazer mais uma operação? (Sim/Não)")
  elif tipoOperacao == "-":
    resultado = num1 - num2
    print(f"O resultado da operação é: {resultado}")
    calcFazer = input("Deseja fazer mais uma operação? (Sim/Não)")
  elif tipoOperacao == "x":
    resultado = num1 * num2
    print(f"O resultado da operação é: {resultado}")
    calcFazer = input("Deseja fazer mais uma operação? (Sim/Não)")
  elif tipoOperacao == "/":
    resultado = num1 / num2
    print(f"O resultado da operação é: {resultado}")
    calcFazer = input("Deseja fazer mais uma operação? (Sim/Não)")
  else:
    print("Operação inválida, digite novamente os valores e a operação")
print(f"Perfeito! Tenha um ótimo dia {nome}!")
#Executa a operação e depois pergunta se o usuário deseja fazer outra operação, caso contrário, ele finalza a aplicação